package com.demo.yiman.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.demo.yiman.bean.NewsDataBean;

import com.demo.yiman.database.NewsDataBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsDataBeanDaoConfig;

    private final NewsDataBeanDao newsDataBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsDataBeanDaoConfig = daoConfigMap.get(NewsDataBeanDao.class).clone();
        newsDataBeanDaoConfig.initIdentityScope(type);

        newsDataBeanDao = new NewsDataBeanDao(newsDataBeanDaoConfig, this);

        registerDao(NewsDataBean.class, newsDataBeanDao);
    }
    
    public void clear() {
        newsDataBeanDaoConfig.clearIdentityScope();
    }

    public NewsDataBeanDao getNewsDataBeanDao() {
        return newsDataBeanDao;
    }

}
