package com.demo.yiman.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.demo.yiman.bean.NewsDataBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NEWS_DATA_BEAN".
*/
public class NewsDataBeanDao extends AbstractDao<NewsDataBean, Long> {

    public static final String TABLENAME = "NEWS_DATA_BEAN";

    /**
     * Properties of entity NewsDataBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property IdSs = new Property(0, Long.class, "idSs", true, "_id");
        public final static Property ItemType = new Property(1, int.class, "itemType", false, "ITEM_TYPE");
        public final static Property Uniquekey = new Property(2, String.class, "uniquekey", false, "UNIQUEKEY");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property Date = new Property(4, String.class, "date", false, "DATE");
        public final static Property Category = new Property(5, String.class, "category", false, "CATEGORY");
        public final static Property Author_name = new Property(6, String.class, "author_name", false, "AUTHOR_NAME");
        public final static Property Url = new Property(7, String.class, "url", false, "URL");
        public final static Property Thumbnail_pic_s = new Property(8, String.class, "thumbnail_pic_s", false, "THUMBNAIL_PIC_S");
        public final static Property Thumbnail_pic_s02 = new Property(9, String.class, "thumbnail_pic_s02", false, "THUMBNAIL_PIC_S02");
        public final static Property Thumbnail_pic_s03 = new Property(10, String.class, "thumbnail_pic_s03", false, "THUMBNAIL_PIC_S03");
    }


    public NewsDataBeanDao(DaoConfig config) {
        super(config);
    }
    
    public NewsDataBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEWS_DATA_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: idSs
                "\"ITEM_TYPE\" INTEGER NOT NULL ," + // 1: itemType
                "\"UNIQUEKEY\" TEXT," + // 2: uniquekey
                "\"TITLE\" TEXT," + // 3: title
                "\"DATE\" TEXT," + // 4: date
                "\"CATEGORY\" TEXT," + // 5: category
                "\"AUTHOR_NAME\" TEXT," + // 6: author_name
                "\"URL\" TEXT," + // 7: url
                "\"THUMBNAIL_PIC_S\" TEXT," + // 8: thumbnail_pic_s
                "\"THUMBNAIL_PIC_S02\" TEXT," + // 9: thumbnail_pic_s02
                "\"THUMBNAIL_PIC_S03\" TEXT);"); // 10: thumbnail_pic_s03
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEWS_DATA_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NewsDataBean entity) {
        stmt.clearBindings();
 
        Long idSs = entity.getIdSs();
        if (idSs != null) {
            stmt.bindLong(1, idSs);
        }
        stmt.bindLong(2, entity.getItemType());
 
        String uniquekey = entity.getUniquekey();
        if (uniquekey != null) {
            stmt.bindString(3, uniquekey);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(5, date);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(6, category);
        }
 
        String author_name = entity.getAuthor_name();
        if (author_name != null) {
            stmt.bindString(7, author_name);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(8, url);
        }
 
        String thumbnail_pic_s = entity.getThumbnail_pic_s();
        if (thumbnail_pic_s != null) {
            stmt.bindString(9, thumbnail_pic_s);
        }
 
        String thumbnail_pic_s02 = entity.getThumbnail_pic_s02();
        if (thumbnail_pic_s02 != null) {
            stmt.bindString(10, thumbnail_pic_s02);
        }
 
        String thumbnail_pic_s03 = entity.getThumbnail_pic_s03();
        if (thumbnail_pic_s03 != null) {
            stmt.bindString(11, thumbnail_pic_s03);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NewsDataBean entity) {
        stmt.clearBindings();
 
        Long idSs = entity.getIdSs();
        if (idSs != null) {
            stmt.bindLong(1, idSs);
        }
        stmt.bindLong(2, entity.getItemType());
 
        String uniquekey = entity.getUniquekey();
        if (uniquekey != null) {
            stmt.bindString(3, uniquekey);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(5, date);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(6, category);
        }
 
        String author_name = entity.getAuthor_name();
        if (author_name != null) {
            stmt.bindString(7, author_name);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(8, url);
        }
 
        String thumbnail_pic_s = entity.getThumbnail_pic_s();
        if (thumbnail_pic_s != null) {
            stmt.bindString(9, thumbnail_pic_s);
        }
 
        String thumbnail_pic_s02 = entity.getThumbnail_pic_s02();
        if (thumbnail_pic_s02 != null) {
            stmt.bindString(10, thumbnail_pic_s02);
        }
 
        String thumbnail_pic_s03 = entity.getThumbnail_pic_s03();
        if (thumbnail_pic_s03 != null) {
            stmt.bindString(11, thumbnail_pic_s03);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NewsDataBean readEntity(Cursor cursor, int offset) {
        NewsDataBean entity = new NewsDataBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // idSs
            cursor.getInt(offset + 1), // itemType
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // uniquekey
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // date
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // category
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // author_name
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // url
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // thumbnail_pic_s
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // thumbnail_pic_s02
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // thumbnail_pic_s03
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NewsDataBean entity, int offset) {
        entity.setIdSs(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setItemType(cursor.getInt(offset + 1));
        entity.setUniquekey(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDate(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCategory(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setAuthor_name(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUrl(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setThumbnail_pic_s(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setThumbnail_pic_s02(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setThumbnail_pic_s03(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NewsDataBean entity, long rowId) {
        entity.setIdSs(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NewsDataBean entity) {
        if(entity != null) {
            return entity.getIdSs();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NewsDataBean entity) {
        return entity.getIdSs() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
